/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1b1e',
        'on-secondary-container': '#626566',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#c4c7ca',
        'outline-variant': '#c4c6cf',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'primary': '#000a1e',
        'surface-tint': '#465f88',
        'inverse-surface': '#2f3033',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#191c1d',
        'on-background': '#1a1b1e',
        'on-tertiary-container': '#85898c',
        'on-secondary-fixed-variant': '#454748',
        'surface-dim': '#dad9dd',
        'primary-fixed-dim': '#aec7f6',
        'surface-container-low': '#f4f3f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e9e7eb',
        'on-primary-fixed': '#001b3d',
        'secondary': '#5c5f60',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f1f0f4',
        'on-primary-container': '#708ab5',
        'on-tertiary-fixed-variant': '#43474a',
        'secondary-container': '#e1e3e4',
        'primary-fixed': '#d6e3ff',
        'background': '#faf9fd',
        'inverse-primary': '#aec7f6',
        'tertiary': '#070b0d',
        'surface': '#faf9fd',
        'surface-bright': '#faf9fd',
        'on-primary-fixed-variant': '#2d476f',
        'error-container': '#ffdad6',
        'tertiary-container': '#1e2224',
        'secondary-fixed': '#e1e3e4',
        'surface-container': '#efedf1',
        'on-tertiary-fixed': '#181c1e',
        'surface-variant': '#e3e2e6',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e3e2e6',
        'outline': '#74777f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'max-width': '1440px',
        'margin-md': '16px',
        'unit': '4px',
        'margin-lg': '32px',
        'container-padding': '24px',
        'margin-sm': '8px',
        'gutter': '16px',
      },
      fontFamily: {
        sans: ['Public Sans', 'system-ui', 'sans-serif'],
        mono: ['Courier Prime', 'monospace'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0.02em', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.02em', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'max-width': '1440px',
      },
    },
  },
  plugins: [],
}
